### ISSUE TITLE
User Story 5: Create a wireframe for the “Registration” page

### ISSUE THREAD

**Issue by zRedwind2** [zRedwind2/Moffat-Bay#15]

**Comment by JDGinter** [comment]
![Image](https://github.com/user-attachments/assets/3510fff8-1a60-498a-9220-6de11bc37f8b)

**Comment by zRedwind2** [comment]
Revised wireframe based on feedback from client.


![Image](https://github.com/user-attachments/assets/da8afb8c-b17d-41b9-9981-597b7db76479)
