### ISSUE TITLE
User Story 7: Create a wireframe for the “Lodge Reservation” page

### ISSUE THREAD

**Issue by zRedwind2** [zRedwind2/Moffat-Bay#17]

**Comment by ACW-Bellevue** [comment]
![Image](https://github.com/user-attachments/assets/e9ef72ef-78a3-4842-b57b-9bf5b4964b3d)

**Comment by ACW-Bellevue** [comment]
![Image](https://github.com/user-attachments/assets/88d96da3-9464-4e9e-bbc7-14a32882fed9)

**Comment by ACW-Bellevue** [comment]
![Image](https://github.com/user-attachments/assets/3654fe51-538e-43f8-a551-545823ffa75c)

**Comment by ACW-Bellevue** [comment]
![Image](https://github.com/user-attachments/assets/0a65c961-a436-49a2-bf82-394846dfa9bd)

**Comment by ghost** [comment]
![Image](https://github.com/user-attachments/assets/0130aaac-d3b3-4254-976c-e5b3ca1a933f)

**Comment by ghost** [comment]
![Image](https://github.com/user-attachments/assets/33f8d990-f495-4f2a-a32e-caad545eacf4)

**Comment by ghost** [comment]
Revised "Lodge Reservation" page incorporating changes requested by the client.

![Image](https://github.com/user-attachments/assets/a127e408-69f2-4e11-8316-2050086280a4)
![Image](https://github.com/user-attachments/assets/08b96570-ce06-4e9d-add6-f56f2842e1c0)
