### ISSUE TITLE
User Story 8: Create a wireframe for the “Reservation Summary” page

### ISSUE THREAD

**Issue by zRedwind2** [zRedwind2/Moffat-Bay#18]

**Comment by levonteabercrombie** [comment]
![Image](https://github.com/user-attachments/assets/7e2e62f5-5c40-4ba6-b69a-60fd3d573202)

**Comment by levonteabercrombie** [comment]
![Image](https://github.com/user-attachments/assets/3b0440d5-d070-4101-adb9-f95ed9d02087)

**Comment by zRedwind2** [comment]
Revised wireframe based on feedback from client.


![Image](https://github.com/user-attachments/assets/fa3d0c72-b5f0-40fe-bd6f-f6000a3bdfe6)
