### ISSUE TITLE
User Story 9: Create a wireframe for the “Reservation Look-Up" page

### ISSUE THREAD

**Issue by zRedwind2** [zRedwind2/Moffat-Bay#19]

**Comment by ACW-Bellevue** [comment]
![Image](https://github.com/user-attachments/assets/6f75d51b-c81e-4867-94bb-8f5345d83b40)

**Comment by ghost** [comment]
![Image](https://github.com/user-attachments/assets/1b954623-4005-4b73-a4db-486811ec4b3a)

**Comment by ghost** [comment]
Revised "Reservation Look Up" page incorporating changes requested by the client.

![Image](https://github.com/user-attachments/assets/3d663a1e-d4e7-4822-bb27-bf6dbe5ad742)
