### ISSUE TITLE
Create three User and Account Table Examples

### ISSUE THREAD

**Issue by zRedwind2** [zRedwind2/Moffat-Bay#26]

**Comment by JDGinter** [comment]
User Table Example:

![Image](https://github.com/user-attachments/assets/adbe47c5-295d-45a5-be0a-ed0c7951e967)

Account Table Example:

![Image](https://github.com/user-attachments/assets/60a3be9c-c929-4ef6-931f-f3377995f7b1)

**Comment by JDGinter** [comment]
USER Table:

![Image](https://github.com/user-attachments/assets/dbd44aa1-eec6-4da7-808e-a6c4e9a8c3cc)

ACCOUNT Table:

![Image](https://github.com/user-attachments/assets/3fdad3b5-e70b-4276-8314-ae0c9acc1b4b)

**Comment by JDGinter** [comment]
USER Table:

![Image](https://github.com/user-attachments/assets/ffb4014d-c2fc-428b-a114-1884d019f6f4)

ACCOUNT Table:

![Image](https://github.com/user-attachments/assets/a7732da1-48e5-430e-ad40-f922ab344a99)

Version 3
