### ISSUE TITLE
Create three Bookings Table Examples

### ISSUE THREAD

**Issue by zRedwind2** [zRedwind2/Moffat-Bay#27]

**Comment by JDGinter** [comment]
BOOKINGS Table:

![Image](https://github.com/user-attachments/assets/bb16e65e-68c9-4b98-9340-f0141272e6e2)

Note: Bookings and Room Table were combined.

**Comment by JDGinter** [comment]
BOOKINGS Table:

![Image](https://github.com/user-attachments/assets/c680b946-97b6-49f4-8f1d-de6021f939fb)

Version 3

**Comment by zRedwind2** [comment]
Changed MySQL ERD and code to no longer have Room_ID. Will add back at later date of development if needed.



![Image](https://github.com/user-attachments/assets/560888e4-8900-468e-a4ee-b7365f2789b3)
